// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2IVkpGHH9EIFx-GOo0HmGwq631UZ_o4',
    appId: '1:380190048310:web:f8fbc80312873667efd897',
    messagingSenderId: '380190048310',
    projectId: 'chat-app-2b86b',
    authDomain: 'chat-app-2b86b.firebaseapp.com',
    storageBucket: 'chat-app-2b86b.appspot.com',
    measurementId: 'G-60VHJYEC8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySRN6y4FzBOZFPSHjmclf9Q_Y7Gy3U7M',
    appId: '1:380190048310:android:8873ef3e806ec095efd897',
    messagingSenderId: '380190048310',
    projectId: 'chat-app-2b86b',
    storageBucket: 'chat-app-2b86b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0ik5ef7dQbrqNWiCDSN3DcbiEI5ekAw',
    appId: '1:380190048310:ios:ebd95591ae16656cefd897',
    messagingSenderId: '380190048310',
    projectId: 'chat-app-2b86b',
    storageBucket: 'chat-app-2b86b.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd0ik5ef7dQbrqNWiCDSN3DcbiEI5ekAw',
    appId: '1:380190048310:ios:15be3b4838044096efd897',
    messagingSenderId: '380190048310',
    projectId: 'chat-app-2b86b',
    storageBucket: 'chat-app-2b86b.appspot.com',
    iosBundleId: 'com.example.scholarChatSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR2IVkpGHH9EIFx-GOo0HmGwq631UZ_o4',
    appId: '1:380190048310:web:7856510d5b2b4a31efd897',
    messagingSenderId: '380190048310',
    projectId: 'chat-app-2b86b',
    authDomain: 'chat-app-2b86b.firebaseapp.com',
    storageBucket: 'chat-app-2b86b.appspot.com',
    measurementId: 'G-L9WZJX2XQL',
  );

}